[tool.poetry]
name = "qbit-quick"
version = "1.0.0"
description = "qBittorrent racing tools"
authors = ["TwistedSystem <twistedsystem8@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
keywords = ["qBittorrent", "racing"]
packages = [{ include = "qbitquick", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10"
platformdirs = "*"
qbittorrent-api = "*"

[tool.poetry.group.dev.dependencies]
tox = "*"

[tool.poetry.scripts]
qbit-quick = "qbitquick.qbit_quick:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"